name: fpl
channels:
  - conda-forge
  - defaults
dependencies:
  - azure-storage-blob>=12.8.1,<13.0.0
  - python-dotenv>=0.19.0,<0.20.0
  - tqdm>=4.62.2,<5.0.0
  - python>=3.8,<3.11
  - PyYAML>=5.4.1,<6.0.0
  - click>=8.0.1,<9.0.0
  - matplotlib>=3.4.3,<4.0.0
  - seaborn>=0.11.2,<0.12.0
  - pandas>=1.3.4,<2.0.0
  - pyarrow>=6,<7
  - mlflow>=1.23.1,<2.0.0
  - boto3>=1.21.3,<2.0.0
  - flake8>=3.9.2,<4.0.0
  - pytest>=6.2.5,<7.0.0
  - pytest-mock>=3.6.1,<4.0.0
  - black>=21.8b0,<22.0
  - isort>=5.9.3,<6.0.0
  - coverage>=5.5,<6.0
  - pre-commit>=2.15.0,<3.0.0
  - pydocstyle>=6.1.1,<7.0.0
  - notebook>=6.4.3,<7.0.0
  - jupytext>=1.12.0,<2.0.0
  - pylint>=2.12.1,<3.0.0
  - rope>=0.22.0,<0.23.0
  - pip
  - pip:
    - jupyter-contrib-nbextensions>=0.5.1,<0.6.0
